import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'pathe'
import { configDefaults, defineConfig } from 'vitest/config'

const currentDir = dirname(fileURLToPath(import.meta.url))

export default defineConfig({
  resolve: {
    alias: {
      // Several specs exercise the app-side stores of `@histoire/app`, which
      // import `vue`. Vue is only installed in that package, so a spec driving
      // their reactivity needs an explicit path to the very entry the stores
      // themselves resolve (one shared Vue instance).
      'vue': resolve(currentDir, '../histoire-app/node_modules/vue/index.mjs'),
      // Those app modules also read the user config, which only exists as a
      // virtual module generated by the Vite plugin at dev/build time.
      'virtual:$histoire-config': resolve(currentDir, 'src/node/__tests__/utils/histoire-config-stub.ts'),
    },
  },
  test: {
    exclude: [...configDefaults.exclude, '**/mcp/integration/**', '**/embed/integration/**', '**/embed/consumers/**', '**/mcp/package-smoke.spec.ts'],
    testTimeout: 15_000,
  },
})
