export const STATE_SYNC = '__histoire:state-sync'
export const SANDBOX_READY = '__histoire:sandbox-ready'
export const EVENT_SEND = '__histoire:event'
export const PREVIEW_SETTINGS_SYNC = '__histoire:preview-settings-sync'
export const SELECT_VARIANT = '__histoire:select-variant'
export const VARIANT_READY = '__histoire:variant-ready'
