import type { ReactStorySetupApi, ReactStorySetupHandler } from '../helpers.js'
import { withStoryExecution } from '@histoire/shared'
// @ts-expect-error Generated by Histoire's Vite plugin.
import * as generatedSetup from 'virtual:$histoire-generated-global-setup'
// @ts-expect-error Generated by Histoire's Vite plugin.
import * as setup from 'virtual:$histoire-setup'

/** Invoke generated, user, and variant setup in order under captured mount ownership. */
export async function callSetupFunctions(api: ReactStorySetupApi, target: Node) {
  const isActive = api.isActive ?? (() => true)
  const handlers = [generatedSetup.setupReact, setup.setupReact, api.variant?.setupApp] as (ReactStorySetupHandler | undefined)[]
  for (const handler of handlers) {
    if (!isActive()) return
    if (typeof handler !== 'function') continue
    const wrapper = await withStoryExecution(() => handler(api), target)
    if (wrapper && isActive()) api.addWrapper(wrapper)
  }
}
