blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/histoire-dev/histoire/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Discord Chat
    url: https://discord.gg/KpCnT72rJk
    about: Ask questions and discuss with other Histoire users in real time.