name: Svelte 4 tests

on:
  push:
    branches:
      - main
      - feat/*
      - fix/*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test

    env:
      dir: ./examples/svelte4

    steps:
      - uses: actions/checkout@master

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/Cypress
          key: pnpm-v1-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-v1-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Build book
        working-directory: ${{env.dir}}
        run: pnpm run story:build

      - name: Run tests
        working-directory: ${{env.dir}}
        run: pnpm run ci

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ${{env.dir}}/cypress/screenshots
